/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesSuspenseRouteImport } from './routes/examples.suspense'
import { Route as ExamplesMutationsRouteImport } from './routes/examples.mutations'
import { Route as ExamplesIntroductionRouteImport } from './routes/examples.introduction'
import { Route as ExamplesGettingStartedRouteImport } from './routes/examples.getting-started'
import { Route as ExamplesConclusionRouteImport } from './routes/examples.conclusion'
import { Route as ExamplesBasicQueryRouteImport } from './routes/examples.basic-query'
import { Route as ExamplesAdvancedQueriesRouteImport } from './routes/examples.advanced-queries'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api.users'
import { ServerRoute as ApiUsersIdServerRouteImport } from './routes/api/users.$id'

const rootServerRouteImport = createServerRootRoute()

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSuspenseRoute = ExamplesSuspenseRouteImport.update({
  id: '/suspense',
  path: '/suspense',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesMutationsRoute = ExamplesMutationsRouteImport.update({
  id: '/mutations',
  path: '/mutations',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesIntroductionRoute = ExamplesIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesGettingStartedRoute = ExamplesGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesConclusionRoute = ExamplesConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesBasicQueryRoute = ExamplesBasicQueryRouteImport.update({
  id: '/basic-query',
  path: '/basic-query',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesAdvancedQueriesRoute = ExamplesAdvancedQueriesRouteImport.update({
  id: '/advanced-queries',
  path: '/advanced-queries',
  getParentRoute: () => ExamplesRoute,
} as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersIdServerRoute = ApiUsersIdServerRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersServerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/advanced-queries': typeof ExamplesAdvancedQueriesRoute
  '/examples/basic-query': typeof ExamplesBasicQueryRoute
  '/examples/conclusion': typeof ExamplesConclusionRoute
  '/examples/getting-started': typeof ExamplesGettingStartedRoute
  '/examples/introduction': typeof ExamplesIntroductionRoute
  '/examples/mutations': typeof ExamplesMutationsRoute
  '/examples/suspense': typeof ExamplesSuspenseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/advanced-queries': typeof ExamplesAdvancedQueriesRoute
  '/examples/basic-query': typeof ExamplesBasicQueryRoute
  '/examples/conclusion': typeof ExamplesConclusionRoute
  '/examples/getting-started': typeof ExamplesGettingStartedRoute
  '/examples/introduction': typeof ExamplesIntroductionRoute
  '/examples/mutations': typeof ExamplesMutationsRoute
  '/examples/suspense': typeof ExamplesSuspenseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/examples/advanced-queries': typeof ExamplesAdvancedQueriesRoute
  '/examples/basic-query': typeof ExamplesBasicQueryRoute
  '/examples/conclusion': typeof ExamplesConclusionRoute
  '/examples/getting-started': typeof ExamplesGettingStartedRoute
  '/examples/introduction': typeof ExamplesIntroductionRoute
  '/examples/mutations': typeof ExamplesMutationsRoute
  '/examples/suspense': typeof ExamplesSuspenseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples'
    | '/examples/advanced-queries'
    | '/examples/basic-query'
    | '/examples/conclusion'
    | '/examples/getting-started'
    | '/examples/introduction'
    | '/examples/mutations'
    | '/examples/suspense'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/examples/advanced-queries'
    | '/examples/basic-query'
    | '/examples/conclusion'
    | '/examples/getting-started'
    | '/examples/introduction'
    | '/examples/mutations'
    | '/examples/suspense'
  id:
    | '__root__'
    | '/'
    | '/examples'
    | '/examples/advanced-queries'
    | '/examples/basic-query'
    | '/examples/conclusion'
    | '/examples/getting-started'
    | '/examples/introduction'
    | '/examples/mutations'
    | '/examples/suspense'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesRoute: typeof ExamplesRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/users' | '/api/users/$id'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/users' | '/api/users/$id'
  id: '__root__' | '/api/users' | '/api/users/$id'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/suspense': {
      id: '/examples/suspense'
      path: '/suspense'
      fullPath: '/examples/suspense'
      preLoaderRoute: typeof ExamplesSuspenseRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/mutations': {
      id: '/examples/mutations'
      path: '/mutations'
      fullPath: '/examples/mutations'
      preLoaderRoute: typeof ExamplesMutationsRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/introduction': {
      id: '/examples/introduction'
      path: '/introduction'
      fullPath: '/examples/introduction'
      preLoaderRoute: typeof ExamplesIntroductionRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/getting-started': {
      id: '/examples/getting-started'
      path: '/getting-started'
      fullPath: '/examples/getting-started'
      preLoaderRoute: typeof ExamplesGettingStartedRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/conclusion': {
      id: '/examples/conclusion'
      path: '/conclusion'
      fullPath: '/examples/conclusion'
      preLoaderRoute: typeof ExamplesConclusionRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/basic-query': {
      id: '/examples/basic-query'
      path: '/basic-query'
      fullPath: '/examples/basic-query'
      preLoaderRoute: typeof ExamplesBasicQueryRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/advanced-queries': {
      id: '/examples/advanced-queries'
      path: '/advanced-queries'
      fullPath: '/examples/advanced-queries'
      preLoaderRoute: typeof ExamplesAdvancedQueriesRouteImport
      parentRoute: typeof ExamplesRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
  }
}

interface ExamplesRouteChildren {
  ExamplesAdvancedQueriesRoute: typeof ExamplesAdvancedQueriesRoute
  ExamplesBasicQueryRoute: typeof ExamplesBasicQueryRoute
  ExamplesConclusionRoute: typeof ExamplesConclusionRoute
  ExamplesGettingStartedRoute: typeof ExamplesGettingStartedRoute
  ExamplesIntroductionRoute: typeof ExamplesIntroductionRoute
  ExamplesMutationsRoute: typeof ExamplesMutationsRoute
  ExamplesSuspenseRoute: typeof ExamplesSuspenseRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  ExamplesAdvancedQueriesRoute: ExamplesAdvancedQueriesRoute,
  ExamplesBasicQueryRoute: ExamplesBasicQueryRoute,
  ExamplesConclusionRoute: ExamplesConclusionRoute,
  ExamplesGettingStartedRoute: ExamplesGettingStartedRoute,
  ExamplesIntroductionRoute: ExamplesIntroductionRoute,
  ExamplesMutationsRoute: ExamplesMutationsRoute,
  ExamplesSuspenseRoute: ExamplesSuspenseRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

interface ApiUsersServerRouteChildren {
  ApiUsersIdServerRoute: typeof ApiUsersIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersIdServerRoute: ApiUsersIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesRoute: ExamplesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
